import random

names = {
    "alvida": ["f","cross guild","paramecia","0","5000000","198","east blue","1","alive","e"],
    "higuma": ["m","goa kingdom","none","0","8000000","190","east blue","1","dead","e"],
    "makino": ["f","goa kingdom","none","0","0","166","east blue","1","alive","e"],
    "woop slap": ["m","goa kingdom","none","0","0","-1","east blue","1","alive","e"],
    "helmeppo": ["m","marines","none","1","1000000","179","east blue","1","alive","e"],
    "koby": ["m","marines","none","3","100000000","167","east blue","1","alive","e"],
    "morgan": ["m","marines","none","0","0","285","east blue","1","alive","e"],
    "beckman": ["m","red haired pirates","none","2","-1","206","north blue","1","alive","e"],
    "lucky roux": ["m","red haired pirates","none","2","-1","241","south blue","1","alive","e"],
    "shanks": ["m","red haired pirates","none","4","4048900000","199","null","1","alive","e"],
    "yasopp": ["m","red haired pirates","none","1","-1","183","east blue","1","alive","e"],
    "roger": ["m","roger pirates","none","4","5564800000","274","east blue","1","dead","e"],
    "koushirou": ["m","shimotsuki village","none","0","0","184","east blue","1","alive","e"],
    "kuina": ["f","shimotsuki village","none","0","0","150","east blue","1","dead","e"],
    "luffy": ["m","straw hats","zoan","4","3000000000","174","east blue","1","alive","e"],
    "zoro": ["m","straw hats","none","4","1111000000","181","east blue","1","alive","e"],
    "buggy": ["m","cross guild","paramecia","0","3189000000","192","east blue","2","alive","e"],
    "cabaji": ["m","cross guild","none","0","0","208","east blue","2","alive","e"],
    "mohji": ["m","cross guild","none","0","0","197","east blue","2","alive","e"],
    "gaimon": ["m","island of rare animals","none","0","0","130","east blue","2","alive","e"],
    "boodle": ["m","orange town","none","0","0","172","east blue","2","alive","e"],
    "rayleigh": ["m","roger pirates","none","4","-1","188","null","2","alive","e"],
    "nami": ["f","straw hats","none","0","366000000","170","east blue","2","alive","e"],
    "kuro": ["m","black cat pirates","none","0","16000000","207","east blue","3","alive","e"],
    "jango": ["m","marines","none","0","1000000","207","east blue","3","alive","e"],
    "usopp": ["m","straw hats","none","1","500000000","176","east blue","3","alive","e"],
    "banchina": ["f","syrup village","none","0","0","-1","east blue","3","dead","e"],
    "kaya": ["f","syrup village","none","0","0","169","east blue","3","alive","e"],
    "merry": ["m","syrup village","none","0","0","-1","east blue","3","alive","e"],
    "zeff": ["m","baratie","none","0","-1","189","east blue","4","alive","e"],
    "johnny": ["m","bounty hunters","none","0","0","186","east blue","4","alive","e"],
    "yosaku": ["m","bounty hunters","none","0","0","185","east blue","4","alive","e"],
    "mihawk": ["m","cross guild","none","3","3590000000","198","null","4","alive","e"],
    "don krieg": ["m","krieg pirates","none","0","17000000","243","east blue","4","alive","e"],
    "gin": ["m","krieg pirates","none","0","12000000","186","east blue","4","alive","e"],
    "pearl": ["m","krieg pirates","none","0","0","239","east blue","4","alive","e"],
    "fullbody": ["m","marines","none","0","1000000","184","north blue","4","alive","e"],
    "sanji": ["m","straw hats","none","3","1032000000","180","north blue","4","alive","e"],
    "arlong": ["m","arlong pirates","none","0","20000000","263","east blue","5","alive","e"],
    "bell-mere": ["f","cocoyashi village","none","0","0","186","east blue","5","dead","e"],
    "genzo": ["m","cocoyashi village","none","0","0","173","east blue","5","alive","e"],
    "nojiko": ["f","cocoyashi village","none","0","0","170","east blue","5","alive","e"],
    "hatchan": ["m","fishman island","none","0","8000000","220","east blue","5","alive","e"],
    "garp": ["m","marines","none","4","3000000000","287","east blue","5","alive","e"],
    "nezumi": ["m","marines","none","0","100000000","182","east blue","5","alive","e"],
    "smoker": ["m","marines","logia","3","500000000","209","east blue","6","alive","e"],
    "tashigi": ["f","marines","none","3","100000000","170","east blue","6","alive","e"],
    "dragon": ["m","revolutionary army","none","0","-1","256","east blue","6","alive","e"],
    "vivi": ["f","alabasta","none","0","0","169","grand line","7","alive","e"],
    "mr 9": ["m","new spiders cafe","none","0","0","-1","grand line","7","alive","e"],
    "crocus": ["m","roger pirates","none","1","-1","203","grand line","7","alive","e"],
    "karoo": ["m","alabasta","none","0","0","150","grand line","8","alive","e"],
    "gem": ["m","new spiders cafe","paramecia","0","0","197","south blue","8","alive","e"],
    "mikita": ["f","new spiders cafe","paramecia","0","0","177","west blue","8","alive","e"],
    "robin": ["f","straw hats","paramecia","0","930000000","188","west blue","8","alive","e"],
    "crocodile": ["m","cross guild","logia","3","1965000000","253","grand line","9","alive","e"],
    "galdino": ["m","cross guild","paramecia","0","24000000","179","south blue","9","alive","e"],
    "marianne": ["f","new spiders cafe","none","0","0","145","north blue","9","alive","e"],
    "brogy": ["m","giants","none","0","1800000000","2130","grand line","9","alive","e"],
    "dorry": ["m","giants","none","0","1800000000","2260","grand line","9","alive","e"],
    "bentham": ["n","straw hats","paramecia","0","32000000","238","east blue","9","alive","e"],
    "hiruluk": ["m","drum kingdom","none","0","0","213","grand line","10","alive","e"],
    "kureha": ["f","drum kingdom","none","0","0","188","grand line","10","alive","e"],
    "wapol": ["m","evil black drum kingdom","paramecia","0","0","207","south blue","10","alive","e"],
    "chopper": ["m","straw hats","zoan","0","1000","90","grand line","10","alive","e"],
    "ace": ["m","whitebeard pirates","logia","4","550000000","185","south blue","10","dead","e"],
    "chaka": ["m","alabasta","zoan","0","0","213","grand line","11","alive","e"],
    "koza": ["m","alabasta","none","0","0","177","grand line","11","alive","e"],
    "pell": ["m","alabasta","zoan","0","0","189","grand line","11","alive","e"],
    "toto": ["m","alabasta","none","0","0","-1","grand line","11","alive","e"],
    "babe": ["m","new spiders cafe","none","0","0","218","grand line","11","alive","e"],
    "daz bonez": ["m","cross guild","paramecia","0","75000000","212","west blue","11","alive","e"],
    "drophy": ["f","new spiders cafe","zoan","0","0","156","grand line","11","alive","e"],
    "lassoo": ["m","new spiders cafe","zoan","0","0","-1","null","11","alive","h"],
    "zala": ["f","new spiders cafe","paramecia","0","0","187","grand line","11","alive","e"],
    "camie": ["f","fishman island","none","0","0","197","grand line","11","alive","e"],
    "hina": ["f","marines","paramecia","0","200000000","181","west blue","11","alive","e"],
    "burgess": ["m","blackbeard pirates","paramecia","3","20000000","355","grand line","12","alive","e"],
    "doc q": ["m","blackbeard pirates","paramecia","0","72000000","342","north blue","12","alive","e"],
    "laffitte": ["m","blackbeard pirates","null","0","42200000","340","west blue","12","alive","e"],
    "teach": ["m","blackbeard pirates","logia","3","3996000000","344","grand line","12","alive","e"],
    "van augur": ["m","blackbeard pirates","paramecia","0","64000000","340","east blue","12","alive","e"],
    "ju peter": ["m","celestial dragons","zoan","1","0","-1","red line","12","alive","e"],
    "mars": ["m","celestial dragons","zoan","6","0","-1","red line","12","alive","e"],
    "saturn": ["m","celestial dragons","zoan","6","0","-1","red line","12","dead","e"],
    "v. nusjuro": ["m","celestial dragons","zoan","3","0","-1","red line","12","alive","e"],
    "warcury": ["m","celestial dragons","zoan","6","0","-1","red line","12","alive","e"],
    "bellamy": ["m","donquixote family","paramecia","3","195000000","240","north blue","12","alive","e"],
    "doflamingo": ["m","donquixote family","paramecia","4","340000000","305","red line","12","alive","e"],
    "sengoku": ["m","marines","zoan","4","0","278","south blue","12","alive","e"],
    "tsuru": ["f","marines","paramecia","3","500000000","204","north blue","12","alive","e"],
    "kuma": ["m","revolutionary army","paramecia","3","296000000","689","south blue","12","unknown","e"],
    "cricket": ["m","saruyama alliance","none","0","0","242","north blue","12","alive","e"],
    "jozu": ["m","whitebeard pirates","paramecia","3","-1","503","west blue","12","alive","e"],
    "marco": ["m","whitebeard pirates","zoan","3","1374000000","203","grand line","12","alive","e"],
    "newgate": ["m","whitebeard pirates","paramecia","4","5046000000","666","grand line","12","dead","e"],
    "eneru": ["m","god's army","logia","1","0","266","sky islands","13","alive","e"],
    "gedatsu": ["m","god's army","none","1","0","220","sky islands","13","alive","e"],
    "hotori": ["m","god's army","none","1","0","179","sky islands","13","unknown","e"],
    "kotori": ["m","god's army","none","1","0","179","sky islands","13","unknown","e"],
    "ohm": ["m","god's army","none","1","0","189","sky islands","13","unknown","e"],
    "satori": ["m","god's army","none","1","0","179","sky islands","13","unknown","e"],
    "shura": ["m","god's army","none","1","0","191","sky islands","13","unknown","e"],
    "yama": ["m","god's army","none","0","0","366","sky islands","13","unknown","e"],
    "noland": ["m","lvneel","none","0","0","220","north blue","13","dead","e"],
    "aisa": ["f","skypiea","none","1","0","140","sky islands","13","alive","e"],
    "conis": ["f","skypiea","none","0","0","176","sky islands","13","alive","e"],
    "gan fall": ["m","skypiea","none","0","0","180","sky islands","13","alive","e"],
    "kalgara": ["m","skypiea","none","1","0","222","sky islands","13","dead","e"],
    "mckinley": ["m","skypiea","none","0","0","-1","sky islands","13","alive","e"],
    "pagaya": ["m","skypiea","none","0","0","179","sky islands","13","alive","e"],
    "kuzan": ["m","blackbeard pirates","logia","3","0","298","south blue","14","alive","e"],
    "foxy": ["m","foxy pirates","paramecia","0","24000000","180","south blue","14","alive","e"],
    "chimney": ["f","water 7","none","0","0","115","grand line","14","alive","e"],
    "kokoro": ["f","water 7","none","0","0","168","grand line","14","alive","e"],
    "blueno": ["m","cp0","paramecia","3","0","258","north blue","15","alive","e"],
    "kaku": ["m","cp0","zoan","3","0","193","east blue","15","alive","e"],
    "kalifa": ["f","cp0","paramecia","3","0","185","grand line","15","alive","e"],
    "lucci": ["m","cp0","zoan","3","0","212","grand line","15","alive","e"],
    "franky": ["m","straw hats","none","0","3940000000","240","south blue","15","alive","e"],
    "iceberg": ["m","water 7","none","0","0","199","grand line","15","alive","e"],
    "paulie": ["m","water 7","none","0","0","195","grand line","15","alive","e"],
    "tom": ["m","water 7","none","0","0","296","grand line","15","dead","e"],
    "jabra": ["m","cp0","zoan","3","0","212","north blue","16","alive","e"],
    "kumadori": ["m","cp0","none","3","0","338","south blue","16","alive","e"],
    "spandam": ["m","cp0","none","0","0","192","grand line","16","alive","e"],
    "saul": ["m","giants","none","0","0","1950","south blue","16","alive","e"],
    "sakazuki": ["m","marines","logia","3","5000000000","306","north blue","16","alive","e"],
    "clover": ["m","ohara","none","0","0","172","west blue","16","dead","e"],
    "olvia": ["f","ohara","none","0","0","186","west blue","16","dead","e"],
    "t bone": ["m","marines","none","8","500000000","200","grand line","16","dead","e"],
    "oars": ["m","giants","none","0","0","6700","north blue","18","dead","e"],
    "yorki": ["m","rumbar pirates","none","0","-1","-1","west blue","18","dead","e"],
    "brook": ["m","straw hats","paramecia","0","383000000","277","west blue","18","alive","e"],
    "absalom": ["m","thriller bark pirates","paramecia","0","0","195","west blue","18","alive","e"],
    "cindry": ["f","thriller bark pirates","none","0","0","188","west blue","18","dead","e"],
    "hildon": ["m","thriller bark pirates","none","0","0","-1","null","18","dead","e"],
    "hogback": ["m","thriller bark pirates","none","0","0","223","west blue","18","alive","e"],
    "inuppe": ["m","thriller bark pirates","none","0","0","-1","null","18","dead","e"],
    "jigoro": ["m","thriller bark pirates","none","0","0","238","west blue","18","dead","e"],
    "kumashi": ["m","thriller bark pirates","none","0","0","-1","null","18","dead","e"],
    "moria": ["m","thriller bark pirates","paramecia","0","320000000","692","west blue","18","alive","e"],
    "perona": ["f","thriller bark pirates","paramecia","0","0","160","west blue","18","alive","e"],
    "ryuma": ["m","thriller bark pirates","none","2","0","179","grand line","18","dead","e"],
    "apoo": ["m","beast pirates","paramecia","3","350000000","256","grand line","19","unknown","e"],
    "hawkins": ["m","beast pirates","paramecia","3","320000000","210","north blue","19","alive","e"],
    "sentomaru": ["m","egghead","none","3","0","279","grand line","19","alive","e"],
    "urouge": ["m","fallen monk pirates","paramecia","0","108000000","388","sky islands","19","alive","e"],
    "bege": ["m","fire tank pirates","paramecia","0","350000000","166","west blue","19","alive","e"],
    "bepo": ["m","heart pirates","none","0","1500","240","grand line","19","alive","e"],
    "law": ["m","heart pirates","paramecia","3","3000000000","191","north blue","19","alive","e"],
    "kidd": ["m","kidd pirates","paramecia","4","3000000000","205","south blue","19","unknown","e"],
    "killer": ["m","kidd pirates","zoan","3","200000000","195","south blue","19","unknown","e"],
    "shakuyaku": ["f","kuja pirates","none","8","0","186","grand line","19","alive","e"],
    "borsalino": ["m","marines","logia","3","3000000000","302","north blue","19","alive","e"],
    "x drake": ["m","marines","zoan","3","0","233","north blue","19","alive","e"],
    "bonney": ["f","straw hats","paramecia","2","320000000","174","red line","19","alive","e"],
    "gloriosa": ["f","kuja pirates","none","0","0","-1","grand line","20","alive","e"],
    "hancock": ["f","kuja pirates","paramecia","4","1659000000","191","grand line","20","alive","e"],
    "marigold": ["f","kuja pirates","zoan","3","40000000","432","grand line","20","alive","e"],
    "sandersonia": ["f","kuja pirates","zoan","3","40000000","453","grand line","20","alive","e"],
    "devon": ["f","blackbeard pirates","paramecia","0","-1","361","south blue","21","alive","e"],
    "shiryu": ["m","blackbeard pirates","paramecia","2","-1","340","grand line","21","alive","e"],
    "hannyabal": ["m","marines","none","0","0","309","south blue","21","alive","e"],
    "inazuma": ["n","revolutionary army","paramecia","0","100000000","228","south blue","21","alive","e"],
    "ivankov": ["n","revolutionary army","paramecia","0","100000000","449","grand line","21","alive","e"],
    "jimbei": ["m","straw hats","none","3","1100000000","301","grand line","21","alive","e"],
    "izo": ["m","whitebeard pirates","none","3","510000000","192","grand line","21","dead","e"],
    "pizarro": ["m","blackbeard pirates","paramecia","0","-1","505","north blue","22","alive","e"],
    "sanjuan wolf": ["m","blackbeard pirates","paramecia","0","-1","18000","west blue","22","alive","e"],
    "vasco shot": ["m","blackbeard pirates","none","0","-1","573","south blue","22","alive","e"],
    "rouge": ["f","roger pirates","none","0","0","-1","south blue","22","dead","e"],
    "little oars jr": ["m","whitebeard pirates","none","0","550000000","6000","grand line","22","dead","e"],
    "vista": ["m","whitebeard pirates","none","3","-1","328","north blue","22","alive","e"],
    "bluejam": ["m","bluejam pirates","none","0","14300000","261","east blue","23","dead","e"],
    "porchemy": ["m","bluejam pirates","none","0","3400000","320","east blue","23","dead","e"],
    "browndros beardriguez": ["m","donquixote family","none","0","0","691","grand line","23","alive","e"],
    "dadan": ["f","goa kingdom","none","0","0","221","east blue","23","alive","e"],
    "stelly": ["m","goa kingdom","none","0","0","180","east blue","23","alive","e"],
    "sabo": ["m","revolutionary army","logia","3","602000000","187","east blue","23","alive","e"],
    "caribou": ["m","caribou","logia","0","210000000","228","north blue","24","alive","e"],
    "demalo black": ["m","fake kidd pirates","none","0","26000000","245","east blue","24","alive","e"],
    "linlin": ["f","big mom pirates","paramecia","4","4388000000","880","grand line","25","unknown","e"],
    "aladdin": ["m","fishman island","none","0","-1","627","grand line","25","alive","e"],
    "den": ["m","fishman island","none","0","0","435","grand line","25","alive","e"],
    "fisher tiger": ["m","fishman island","none","0","230000000","520","grand line","25","dead","e"],
    "neptune": ["m","fishman island","none","0","0","1220","grand line","25","alive","e"],
    "shirahoshi": ["f","fishman island","none","1","0","1187","grand line","25","alive","e"],
    "hordy jones": ["m","new fishman pirates","none","0","0","331","grand line","25","alive","e"],
    "vander decken ix": ["m","new fishman pirates","paramecia","0","0","352","grand line","25","alive","e"],
    "koala": ["f","revolutionary army","none","0","-1","160","null","25","alive","e"],
    "pekoms": ["m","zou","zoan","3","330000000","232","grand line","25","alive","e"],
    "otohime": ["f","fishman island","none","1","0","224","grand line","25","dead","e"],
    "buffalo": ["m","donquixote family","paramecia","0","0","696","north blue","26","alive","e"],
    "caesar clown": ["m","donquixote family","logia","0","300000000","309","grand line","26","alive","e"],
    "monet": ["f","donquixote family","logia","0","0","227","north blue","26","alive","e"],
    "kin'emon": ["m","kozuki clan","none","3","0","295","grand line","26","alive","e"],
    "momonosuke": ["m","kozuki clan","zoan","1","0","322","grand line","26","alive","e"],
    "baby 5": ["f","straw hats","paramecia","0","0","181","west blue","26","alive","e"],
    "kaido": ["m","beast pirates","zoan","4","4611100000","710","grand line","27","unknown","e"],
    "kanjuro": ["m","beast pirates","paramecia","0","0","347","grand line","27","dead","e"],
    "guernika": ["m","cp0","none","0","0","243","west blue","27","alive","e"],
    "dellinger": ["m","donquixote family","none","0","15000000","145","north blue","27","alive","e"],
    "diamante": ["m","donquixote family","paramecia","3","99000000","525","north blue","27","alive","e"],
    "giolla": ["f","donquixote family","paramecia","0","0","221","north blue","27","alive","e"],
    "gladius": ["m","donquixote family","paramecia","0","31000000","260","north blue","27","alive","e"],
    "homing": ["m","donquixote family","none","0","0","-1","red line","27","dead","e"],
    "lao g": ["m","donquixote family","none","0","61000000","157","north blue","27","alive","e"],
    "machvise": ["m","donquixote family","paramecia","0","11000000","440","north blue","27","alive","e"],
    "pica": ["m","donquixote family","paramecia","3","99000000","470","north blue","27","alive","e"],
    "senor pink": ["m","donquixote family","paramecia","0","58000000","244","north blue","27","alive","e"],
    "sugar": ["f","donquixote family","paramecia","0","0","110","north blue","27","alive","e"],
    "trebol": ["m","donquixote family","paramecia","3","99000000","349","north blue","27","alive","e"],
    "vergo": ["m","donquixote family","none","3","0","247","north blue","27","alive","e"],
    "rebecca": ["f","dressrosa","none","1","0","171","grand line","27","alive","e"],
    "riku doldo iii": ["m","dressrosa","none","0","0","261","grand line","27","alive","e"],
    "scarlet": ["f","dressrosa","none","0","0","-1","grand line","27","dead","e"],
    "viola": ["f","dressrosa","paramecia","0","0","178","grand line","27","alive","e"],
    "chinjao": ["m","happo navy","none","4","542000000","520","west blue","27","alive","e"],
    "issho": ["m","marines","paramecia","3","3000000000","270","west blue","27","alive","e"],
    "rosinante": ["m","marines","paramecia","0","1000000","293","north blue","27","dead","e"],
    "hack": ["m","revolutionary army","none","0","0","280","grand line","27","alive","e"],
    "bartolomeo": ["m","straw hats","paramecia","0","200000000","220","east blue","27","alive","e"],
    "cavendish": ["m","straw hats","none","3","330000000","208","grand line","27","alive","e"],
    "hajrudin": ["m","straw hats","none","0","0","2200","grand line","27","alive","e"],
    "leo": ["m","straw hats","paramecia","0","0","23","grand line","27","alive","e"],
    "sai": ["m","straw hats","none","3","210000000","242","west blue","27","alive","e"],
    "maynard": ["m","marines","none","3","500000000","-1","null","27","alive","h"],
    "gotti": ["m","fire tank pirates","none","0","90000000","375","west blue","28","alive","e"],
    "vito": ["m","fire tank pirates","none","0","95000000","242","west blue","28","alive","e"],
    "raizo": ["m","kozuki clan","paramecia","0","0","311","grand line","28","alive","e"],
    "buckingham stussy": ["f","weevil","none","0","0","68","grand line","28","alive","e"],
    "weevil": ["m","weevil","none","3","480000000","680","grand line","28","alive","e"],
    "inuarashi": ["m","whitebeard pirates","none","3","0","511","grand line","28","alive","e"],
    "nekomamushi": ["m","whitebeard pirates","none","3","0","522","grand line","28","alive","e"],
    "carrot": ["f","zou","none","0","0","161","grand line","28","alive","e"],
    "pedro": ["m","zou","none","3","382000000","233","grand line","28","dead","e"],
    "wanda": ["f","zou","none","0","0","181","grand line","28","alive","e"],
    "brulee": ["f","big mom pirates","paramecia","0","0","350","grand line","29","alive","e"],
    "cracker": ["m","big mom pirates","paramecia","3","860000000","307","grand line","29","alive","e"],
    "katakuri": ["m","big mom pirates","paramecia","4","1057000000","509","grand line","29","alive","e"],
    "oven": ["m","big mom pirates","paramecia","3","300000000","492","grand line","29","alive","e"],
    "perospero": ["m","big mom pirates","paramecia","3","700000000","333","grand line","29","alive","e"],
    "smoothie": ["f","big mom pirates","paramecia","3","932000000","464","grand line","29","alive","e"],
    "streusen": ["m","big mom pirates","paramecia","0","0","140","grand line","29","alive","e"],
    "stussy": ["f","cp0","zoan","3","0","179","null","29","alive","e"],
    "ichiji": ["m","germa kingdom","none","0","0","186","north blue","29","alive","e"],
    "judge": ["m","germa kingdom","none","2","0","272","north blue","29","alive","e"],
    "niji": ["m","germa kingdom","none","0","0","185","north blue","29","alive","e"],
    "reiju": ["f","germa kingdom","none","0","0","173","north blue","29","alive","e"],
    "sora": ["f","germa kingdom","none","0","0","-1","north blue","29","dead","e"],
    "yonji": ["m","germa kingdom","none","0","0","194","north blue","29","alive","e"],
    "carmel": ["f","sheep's house","paramecia","0","0","185","west blue","29","dead","e"],
    "morgans": ["m","world economic journal","zoan","0","0","305","grand line","29","alive","e"],
    "aramaki": ["m","marines","logia","3","3000000000","308","south blue","30","alive","e"],
    "belo betty": ["f","revolutionary army","paramecia","3","457000000","196","east blue","30","alive","e"],
    "karasu": ["m","revolutionary army","logia","3","400000000","265","north blue","30","alive","e"],
    "lindbergh": ["m","revolutionary army","none","3","316000000","149","south blue","30","alive","e"],
    "morley": ["m","revolutionary army","paramecia","3","293000000","1253","west blue","30","alive","e"],
    "black maria": ["f","beast pirates","zoan","3","480000000","820","grand line","31","alive","e"],
    "jack": ["m","beast pirates","zoan","3","1000000000","830","grand line","31","alive","e"],
    "king": ["m","beast pirates","zoan","3","1390000000","613","grand line","31","alive","e"],
    "orochi": ["m","beast pirates","zoan","0","0","350","grand line","31","dead","e"],
    "page one": ["m","beast pirates","zoan","3","290000000","171","grand line","31","alive","e"],
    "queen": ["m","beast pirates","zoan","3","1320000000","612","grand line","31","alive","e"],
    "sasaki": ["m","beast pirates","zoan","3","472000000","318","grand line","31","alive","e"],
    "ulti": ["f","beast pirates","zoan","3","400000000","173","grand line","31","alive","e"],
    "who's who": ["m","beast pirates","zoan","3","546000000","336","north blue","31","alive","e"],
    "s-hawk": ["m","cp0","paramecia","3","0","212","null","31","alive","e"],
    "s-snake": ["f","cp0","paramecia","3","0","208","null","31","alive","e"],
    "ashura doji": ["m","kozuki clan","none","3","0","544","grand line","31","dead","e"],
    "denjiro": ["m","kozuki clan","none","3","0","306","grand line","31","alive","e"],
    "hiyori": ["f","kozuki clan","none","0","0","170","grand line","31","alive","e"],
    "hyougoro": ["m","kozuki clan","none","3","0","100","grand line","31","alive","e"],
    "kiku": ["f","kozuki clan","none","3","0","287","grand line","31","alive","e"],
    "shinobu": ["f","kozuki clan","paramecia","0","0","180","grand line","31","alive","e"],
    "sukiyaki": ["m","kozuki clan","none","0","0","214","grand line","31","alive","e"],
    "tama": ["f","kozuki clan","paramecia","0","0","108","grand line","31","alive","e"],
    "toki": ["f","kozuki clan","paramecia","0","0","190","grand line","31","dead","e"],
    "yamato": ["m","kozuki clan","zoan","4","0","263","grand line","31","alive","e"],
    "grus": ["m","marines","null","3","200000000","205","west blue","31","alive","e"],
    "uta": ["f","red haired pirates","paramecia","0","0","169","null","31","unknown","e"],
    "oden": ["m","roger pirates","none","4","-1","382","grand line","31","dead","e"],
    "garling": ["m","celestial dragons","none","0","0","-1","red line","32","alive","e"],
    "york": ["f","celestial dragons","paramecia","0","0","482","null","32","alive","e"],
    "s-bear": ["m","cp0","paramecia","3","0","660","null","32","alive","e"],
    "s-shark": ["m","cp0","paramecia","3","0","320","null","32","alive","e"],
    "atlas": ["f","egghead","paramecia","0","0","729","null","32","alive","e"],
    "edison": ["m","egghead","paramecia","0","0","100","null","32","alive","e"],
    "lilith": ["f","egghead","paramecia","0","0","204","null","32","alive","e"],
    "pythagoras": ["m","egghead","paramecia","0","0","341","null","32","alive","e"],
    "shaka": ["m","egghead","paramecia","0","0","220","null","32","alive","e"],
    "stella": ["m","egghead","paramecia","0","0","314","grand line","32","dead","e"],
    "hibari": ["f","marines","none","3","1000000","165","north blue","32","alive","e"],
    "kujaku": ["f","marines","paramecia","3","200000000","180","north blue","32","alive","e"],
    "ginny": ["f","revolutionary army","none","0","190000000","174","grand line","32","dead","e"],
    "rika": ["f","marines","none","0","0","-1","east blue","1","alive","h"],
    "gaban": ["m","roger pirates","none","0","0","","","2","unknown","h"],
    "pudding pudding": ["m","marines","none","0","0","","","5","dead","h"],
    "stronger ": ["m","blackbeard pirates","zoan","0","0","-1","grand line","12","alive","h"],
    "baron omatsuri": ["m","red arrows","paramecia","0","-1","","null","13","dead","h"],
    "very good": ["m","marines","paramecia","0","100000000","","","16","","h"],
    "seamars": ["m","space pirates","none","0","0","","space","16","","h"],
    "attach": ["m","world economic journal","none","0","0","-1","grand line","17","unknown","h"],
    "faust": ["m","beast pirates","none","0","0","-1","north blue","19","unknown","h"],
    "heracles": ["m","boin archipelago","none","0","0","","south blue","20","alive","h"],
    "kong": ["m","marines","none","8","0","","","21","","h"],
    "mjosgard": ["m","celestial dragons","none","0","0","211","red line","25","dead","h"],
    "joyboy": ["m","joyboy pirates","zoan","5","0","-1","null","25","dead","h"],
    "diez barrels": ["m","barrel pirates","none","0","0","-1","north blue","27","dead","h"],
    "shiki": ["m","golden lion pirates","paramecia","0","0","","","31","unknown","h"],
    "john": ["m","rocks pirates","none","0","0","","","31","dead","h"],
    "ohchoku": ["m","rocks pirates","none","0","0","","","31","dead","h"],
    "silver axe": ["m","rocks pirates","none","0","0","","","31","dead","h"],
    "xebec": ["m","rocks pirates","none","0","0","","","31","dead","h"],
    "nefeltari d. lili": ["f","alabasta","none","0","0","-1","grand line","32","dead","h"],
    "urban": ["m","marines","paramecia","1","500000000","","","32","","h"],
    "akehende": ["m","marines","none","0","200000000","","","","","h"],
    "asahija": ["m","marines","none","0","100000","","","","","h"],
    "bakezo": ["m","marines","none","0","0","","","","","h"],
    "bastille": ["m","marines","none","3","500000000","","","","","h"],
    "bluegrass": ["f","marines","paramecia","8","500000000","","","","","h"],
    "bogard": ["m","marines","none","0","0","","","","","h"],
    "bomba": ["m","marines","none","0","0","","","","","h"],
    "brannew": ["m","marines","none","0","100000000","","","","","h"],
    "cancer": ["m","marines","none","8","500000000","","","","","h"],
    "candre": ["m","marines","none","0","0","","","","","h"],
    "catacombo": ["m","marines","none","0","200000000","","","","","h"],
    "chaton": ["m","marines","none","8","500000000","","","","","h"],
    "comil": ["m","marines","none","8","500000000","","","","","h"],
    "daigin": ["m","marines","none","0","100000000","","","","","h"],
    "dalmation": ["m","marines","zoan","8","500000000","","","","","h"],
    "doberman": ["m","marines","none","8","500000000","","","","","h"],
    "doll": ["f","marines","none","2","500000000","","","","","h"],
    "dr. fishbone": ["m","marines","none","0","0","","","","","h"],
    "draw": ["m","marines","none","2","500000000","","","","","h"],
    "gal": ["m","marines","none","0","0","","","","","h"],
    "gion": ["f","marines","none","8","500000000","","","","","h"],
    "glove": ["m","marines","none","0","0","","","","","h"],
    "gorilla": ["m","marines","none","0","100000000","","","","","h"],
    "guillotine": ["m","marines","none","8","500000000","","","","","h"],
    "hototogishu": ["f","marines","none","8","500000000","","","","","h"],
    "hound": ["m","marines","zoan","8","500000000","","","","","h"],
    "isuka": ["f","marines","none","0","1000000","","","","","h"],
    "jero": ["m","marines","none","0","0","","","","","h"],
    "john giant": ["m","marines","none","8","500000000","","","","alive","h"],
    "kadar": ["m","marines","none","0","200000000","","","","","h"],
    "kibin": ["m","marines","none","0","0","","","","","h"],
    "koda": ["f","marines","none","0","0","","","","","h"],
    "komakkov": ["m","marines","none","0","0","","","","","h"],
    "kyuji": ["m","marines","none","0","0","","","","","h"],
    "lacroix": ["m","marines","none","8","500000000","","","","","h"],
    "lines": ["m","marines","none","0","100000","","","","","h"],
    "lonz": ["m","marines","none","8","500000000","","","","","h"],
    "makko": ["m","marines","none","0","1000000","","","","","h"],
    "mashikaku": ["m","marines","none","0","100000","","","","","h"],
    "momonga": ["m","marines","none","3","500000000","","","","","h"],
    "mozambia": ["m","marines","none","8","500000000","","","","","h"],
    "nazu": ["m","marines","none","8","500000000","","","","","h"],
    "onigumo": ["m","marines","zoan","8","500000000","","","","","h"],
    "pike": ["m","marines","none","0","0","","","","","h"],
    "pomskey": ["m","marines","zoan","8","500000000","","","","","h"],
    "ratel": ["m","marines","none","0","100000000","","","","","h"],
    "red king": ["m","marines","none","8","500000000","","","","","h"],
    "ripper": ["m","marines","none","0","1000000","","east blue","","","h"],
    "rokkaku": ["m","marines","none","0","1000000","","east blue","","","h"],
    "sharinguru": ["m","marines","paramecia","0","100000000","","","","","h"],
    "shine": ["m","marines","none","0","100000","","","","","h"],
    "shu": ["m","marines","paramecia","0","100000000","","","","","h"],
    "sicily": ["m","marines","none","0","200000000","","","","","h"],
    "stainless": ["m","marines","none","8","500000000","","","","","h"],
    "stalker": ["m","marines","none","0","1000000","","","","","h"],
    "strawberry": ["m","marines","none","8","500000000","","","","","h"],
    "tensei": ["m","marines","none","0","0","","","","","h"],
    "tosa": ["m","marines","none","2","500000000","","","","","h"],
    "ukkari": ["m","marines","none","0","100000","","","","","h"],
    "yamakaji": ["m","marines","none","8","500000000","","","","","h"],
    "yarisugi": ["m","marines","none","0","100000000","","","","","h"],
    "zotto": ["m","marines","none","0","1000000","","","","","h"],
    "dalton": ["m","drum kingdom","zoan","0","0","218","grand line","10","alive","e"],
}
arcs = [
    "monsters",
    "romance dawn",
    "orange town",
    "syrup village",
    "baratie",
    "arlong park",
    "lougetown",
    "reverse mountain",
    "whiskey peak",
    "little garden",
    "drum island",
    "arabasta",
    "jaya",
    "skypiea",
    "long ring long land",
    "water 7",
    "enies lobby",
    "post ennies lobby",
    "thriller bark",
    "sabaody archipelago",
    "amazon lily",
    "impel down",
    "marineford",
    "post-war",
    "return to sabaody",
    "fish-man island",
    "punk hazard",
    "dressrosa",
    "zou",
    "whole cake island",
    "reverie",
    "wano country",
    "egghead",
    "elbaph"
]
haki = [
    "no haki",
    "only observation haki",
    "only armament haki",
    "observation and armament haki",
    "conquerer's, observation, and armament haki",
    "only conquerer's haki",
    "conquerer's and observation haki",
    "conquerer's and armament haki",
    "unknown haki"
]
chosen_name = random.choice(list(names.keys()))
chosen_name_traits = names[chosen_name]
hard_mode_toggle1 = False
hard_mode_toggle2 = False
hard_mode = "3"
while not hard_mode_toggle1:
    hard_mode = input("Hard mode? (y/n): ")
    if hard_mode.lower() == "y" or hard_mode.lower() == "n":
        hard_mode_toggle1 = True
        break
    
if hard_mode.lower() == "n":
    while not hard_mode_toggle2:
        if chosen_name_traits[8] == "h":
            chosen_name = random.choice(list(names.keys()))
            chosen_name_traits = names[chosen_name]
        else:
            hard_mode_toggle2 = True

while True:
    guess = input("\nGuess a name: ")
    
    if guess.lower() not in names:
        print("Invalid name, try again.")
        continue
    if guess.lower() == chosen_name.lower():
        print("You guessed correctly!")
        break
    else:
        guess_traits = names[guess.lower()]
        print("Incorrect.")
        print("\nHere are the matching traits between your guess and the chosen name:")
        for i in range(len(guess_traits)):
            if i != 9: 
                if guess_traits[i] == chosen_name_traits[i]:
                    if i == 0:
                        if guess_traits[i] == "m":
                            print(f"🟩 Male")
                        elif guess_traits[i] == "f":
                            print(f"🟩 Female")
                        else:
                            print(f"🟩 Other")
                    elif i == 3:
                        print(f"🟩 {haki[int(guess_traits[3])].capitalize()}")
                    elif i == 7:
                        print(f"🟩 {arcs[int(guess_traits[7])].capitalize()}")
                    else:
                        print(f"🟩 {guess_traits[i].capitalize()}")
                else:
                    if guess_traits[i].isdigit():
                        if i == 3:
                            print(f"🟥 {haki[int(guess_traits[3])].capitalize()}")
                        elif i == 7:
                            if int(guess_traits[i]) < int(chosen_name_traits[i]):
                                print(f"⬆️  {arcs[int(guess_traits[7])].capitalize()}")
                            else:
                                print(f"⬇️  {arcs[int(guess_traits[7])].capitalize()}")
                        else:
                            if int(guess_traits[i]) < int(chosen_name_traits[i]):
                                print(f"⬆️  {guess_traits[i]}")
                            else:
                                print(f"⬇️  {guess_traits[i]}")
                    else:
                        if i == 0:
                            if guess_traits[i] == "m":
                                print(f"🟥 Male")
                            elif guess_traits[i] == "f":
                                print(f"🟥 Female")
                            else:
                                print(f"🟥 Other")
                        elif i == 4:
                            print(f"🟥 Chosen Character's Bounty is unknown")
                        elif i == 5: 
                            print(f"🟥 Chosen Character's Hight is unknown")
                        else:
                            print(f"🟥 {guess_traits[i].capitalize()}")
